name: deepfake_detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.0.1
  - ninja
  - scipy
  - matplotlib
  - tqdm
  - numpy
  - pillow
  - pip:
    - opencv-python>=4.5.0
    - tensorboard>=2.5.0
    - torch>=1.9.0
    - torchvision>=0.10.0
    - facenet-pytorch>=2.5.0
    - pytorchvideo